#!/bin/bash
set -euo pipefail

_build_jar() {
  mvn clean install
}

_publish_jar() {
  local version="$1"
  package_cloud push --url https://packages.shopify.io/ \
    --coordinates com.shopify.data.presto:presto-logging-plugin:$version \
    shopify/public/java/1.8  \
    target/logging-plugin-$version-jar-with-dependencies.jar 
}

main() {
  _build_jar

  local tags=$(git tag -l --points-at HEAD)
  if [ -z "${tags}" ]; then
    echo "Not a tagged commit, not performing release."
    exit
  fi

  # Assume the only tag is of the form "v<VERSION>"
  _publish_jar "${tags:1}"
}

main
